### ISSUE TITLE
Last few characters dropped on tab switch.

### ISSUE THREAD

**Issue by cthurston** [MikeRatcliffe/Acebug#16]
The last few characters typed are lost in the multi-line console when switching between tabs. 

This is being use by about 220 students now and this bug is rather bothersome.  

Mike, if you could give me your best guess on where to look for the fix, I might be able to find it and fix it.  

Thanks,

Chris

**Comment by nightwing** [comment]
try version from v1.5pre branch  https://github.com/MikeRatcliffe/Acebug/zipball/v1.5pre
it solves that problem and adds lots of new features
only problem is that console now is global and have same content  for all firefox tabs (if firebug activated on several tabs), but i think it's better
we probably should release new versions faster with smaller changes

if you can't install from that zip i can send you .xpi file

**Comment by MikeRatcliffe** [comment]
@Chris

If you wait a couple of days the new students will not have to do anything special. Sorry that this is taking so long but I have just started work for Mozilla on their DevTools team and have been busy getting everything up and running. Hopefully I will get some time tomorrow night but certainly will release the extension in the next few days.

**Comment by cthurston** [comment]
Mike this is a great tool.  I understand if you don't have all the time in the world to work on it.  Just giving input because we like it and want to see it get better.  

I tried the pre 1.5 on FF 3.6.15 and FBug 1.7.1b1, but it didn't work.  I will wait for the release.
