### ISSUE TITLE
(probably) old version on mozilla plugins

### ISSUE THREAD

**Issue by carecki** [MikeRatcliffe/Acebug#17]
After installing Acebug from https://addons.mozilla.org/en-US/firefox/addon/acebug/ I got version 1.4, but I doubt that this is the newest one... The options screen looks like this: http://img688.imageshack.us/i/acebug14options.png/ I also don't have Resources tab in firebug.
Don't know whether there are more differences, I mentioned some that I noticed immediately after installing.

**Comment by MikeRatcliffe** [comment]
That is because the new version has not been reviewed yet, sorry for the confusion. They don't provide a system to change the page content only for a particular version.

You can get the new version from:
https://addons.mozilla.org/firefox/downloads/file/118213/acebug-1.5-fx.xpi?src=version-history

**Comment by carecki** [comment]
Thank you for explanation. And direct link.
