### ISSUE TITLE
Ace editor warning:  Infinite loop in validation

### ISSUE THREAD

**Issue by cthurston** [MikeRatcliffe/Acebug#18]
I found this morning that if you type:

if('

while code validation is on it creates an infinite loop.  Because Acebug is global you cannot get out of the loop without restarting the browser.

May be a good idea to set default setting as NOT to validate as you type until ace fixes the bug.

Chris

Firefox 3.6.xx
Windows XP

**Comment by MikeRatcliffe** [comment]
Not good, not good at all. I will see if a bug has been logged and log one if it hasn't.

**Comment by MikeRatcliffe** [comment]
I see that you have already logged one:
https://github.com/ajaxorg/ace/issues/219

**Comment by cthurston** [comment]
This has been fixed in the latest ace.

**Comment by MikeRatcliffe** [comment]
True, but we shouldn't close it here until I upgrade Acebug to use the latest Ace. I am planning on doing it this weekend so if you have any changes that you want to be in that version you should send them to me.
