### ISSUE TITLE
Save button no longer auto appends .js (won't save if .js isn't typed)

### ISSUE THREAD

**Issue by cthurston** [MikeRatcliffe/Acebug#19]
Clicking on the save button in the bottom right brings up the prompt to save.  If you don't type at least a . after the name typed in the save dialogue it will not save the file at all.  

If I remember correctly 1.4 would append the .js.  Don't know how that broke in 1.5. 

Chris

**Comment by nightwing** [comment]
my fault:(
fixed at
https://github.com/MikeRatcliffe/Acebug/commit/eac869bf857d266a3641183a855cb02c8bc872cf

thanks for noticing this.
