### ISSUE TITLE
In Minefield Ace JavaScript validation throws a bunch of Chrome errors 

### ISSUE THREAD

**Issue by MikeRatcliffe** [MikeRatcliffe/Acebug#2]
In Minefield Ace validates the JavaScript as you type but this throws a bunch of Chrome errors in the console:
uncaught exception: [Exception... "Component returned failure code: 0x80530019 [nsIWorkerScope.postMessage]"  nsresult: "0x80530019 (<unknown>)"  location: "JS frame :: chrome://acebug/content/ace/lib/ace/worker/host.js :: <TOP_LEVEL> :: line 3"  data: no]

**Comment by nightwing** [comment]
in latest version validation works on ff4, but not in 3.6
on devel i temporary disabled it, we can add it back when it works better

**Comment by MikeRatcliffe** [comment]
I see that you have been busy ... do I see correctly that you have even updated to a more recent version of Ace?

We can leave this open until the validation is working because I think it is a cool feature. It is just a shame that it randomly deletes lines.
