### ISSUE TITLE
Locks browser on refresh while worker is active.

### ISSUE THREAD

**Issue by cthurston** [MikeRatcliffe/Acebug#21]
If you refresh the browser and begin editing the multi-line ace console before the page is completely reloaded it will freeze the browser.  I couldn't reproduce the error with ace in the browser window so I'm pretty sure it is breaking at the Acebug level.  It only freezes the browser if the code validation is on.  Anyway to force the validation worker to wait until the entire page is refreshed?  Or package the scripts so it doesn't hang?

I'm not sure where to even look for a fix.  Any ideas?

Chris

**Comment by cthurston** [comment]
It actually will freeze when any GET is loading.  This may be an ace issue.  I suppose it could be tested by embedding ace in a web page and try to edit while other assets are loading.

**Comment by cthurston** [comment]
Another thought while I'm here:  Since the worker is problematic, could it be set in Ace to only check the document on enter press at the end of a line input and not onChange?  It is not very useful to check for a missing bracket while you are typing the contents inside of the bracket.

**Comment by nightwing** [comment]
Chris Acebug 1.8 uses entirely different mechanism for validation similar to the one proposed in your comment

if you still use acebug can you check if this issue is fixed,  and validation works on slower systems.
thanks

**Comment by nightwing** [comment]
closing this issue as `probablyWorks`
Chris if you are still using aceBug and still see this bug feel free to reopen it

and thanks for the idea!
