### ISSUE TITLE
Inactive Resource Panel

### ISSUE THREAD

**Issue by NickGrease** [MikeRatcliffe/Acebug#22]
Firefox 4.0.1 w/ Firebug 1.7.2 and Acebug 1.5 - Using clean profile

Resource panel inactive - Trying to enable using the tabs mini-menu or the hyperlink on the tab does nothing. Using the Firefox menu button and selecting 'Enable All Panels' does not enable the panel.

**Comment by nightwing** [comment]
thank you for reporting this bug.
fixed this in commit  99d7d1f9e4f234aea4fe
