### ISSUE TITLE
let statements

### ISSUE THREAD

**Issue by ghost** [MikeRatcliffe/Acebug#23]
let statements are shown as an error.
https://developer.mozilla.org/en/JavaScript/Reference/Statements/let

**Comment by nightwing** [comment]
error reporting comes from ace, which uses jshint for it

things hopefully will improve once jshint gets better parser
https://github.com/jshint/jshint/commit/fb2fc8fe2f10ee43f4b4132e96572bd13415a020

**Comment by nightwing** [comment]
with 62542433fc1585d4a415bfc81da42d1faeaff5d1 let statements are shown as warning which isn't that bad
