### ISSUE TITLE
font size in console window 

### ISSUE THREAD

**Issue by asifashraf** [MikeRatcliffe/Acebug#25]
I am being pissed off with the small font size in the console window. I have tried a lots of ways and finally I reached the file theme-twilight.js where I was able to figure out a little bit. But when I added font-size: 18px; property to a keyword style and re-installed the AceBug. The cursor started doing strange behavior. So my question is what is the best way to increase Font Size in the Javascript console editor(Multi line of course) and Why don't you guys add that feature in the AceBug by default?

**Comment by nightwing** [comment]
thanks for reporting this bug.
this worked in previous version but was broken while updating for firebug 1.8

you can add
`*{font-size: 18px;}`
to `theme-twilight.js`
as a temporary workaround untill this is fixed

**Comment by asifashraf** [comment]
As a workaround I had to add this font-size property on many selectors BUT it worked for me. But yes its extremely good if you guys do something like it should increase from options. thanks

**Comment by davidlgj** [comment]
An option to set font size would be great... maybe I'm half blind but I can barely use it as it is now.

**Comment by wangyu0248** [comment]
Very Helpfull!  Thanks a lot

**Comment by nightwing** [comment]
added in https://addons.mozilla.org/en-us/firefox/addon/acebug/versions/?page=1#version-1.10.0
