### ISSUE TITLE
Save Enhancements

### ISSUE THREAD

**Issue by madmod** [MikeRatcliffe/Acebug#27]
A save hotkey would be nice. Also the option to overwrite without prompting, e.g. save vs save as functionality in a text editor.

**Comment by MikeRatcliffe** [comment]
Sounds like a good idea ... to be honest I am surprised that we have not yet added this.

**Comment by nightwing** [comment]
> to be honest I am surprised that we have not yet added this.

@MikeRatcliffe he-he someone was saying `I really don't think we need a "save", "save as" is plenty here` :)
but that was in january

@madmod just commited fix for this bug 69ab8ac, i assume you figured out how to use development version and can test it
if no i can make a test build for you

probably acebug needs to automatically save contents of console when closing (if no file is loaded) as well

**Comment by nightwing** [comment]
> compatibility saying that the extension was corrupt
> strange. was install.rdf in the top level of your .xpi?

build is here https://github.com/downloads/nightwing/Acebug/Acebug.xpi

but if you want to hack on the code its better to follow this page
https://developer.mozilla.org/en/Setting_up_extension_development_environment#Custom_code_location
and load extension directly from the folder without .xpi

**Comment by nightwing** [comment]
somehow forgot about hotkey, thanks for reminding
i've updated the build and both problems should be fixed now.

> Thanks for the awesome support.

we just love 5star reviews :-)

Thanks for your help.

**Comment by nightwing** [comment]
strange. 
it works for me with bot ff5+firebug1.8, and nightly+firebug1.9a 
sometimes, when installing addons not from Mozilla's site, addonManager doesn't cleanup caches properly, maybe that's the issue?
can you try again?

btw. white background means ace wasn't loaded at all, it can't change your preferences.

**Comment by nightwing** [comment]
hi
sorry for late response,

> Acebug from the master branch with the same result

if you installed it as unpacked addon, it might be problem with submodule.
anyway i've removed submodule and updated version of ace
can you test latest from master or
https://github.com/downloads/nightwing/Acebug/Acebug2.xpi

and if those don't work either do you see any errors in firefox error console?

**Comment by nightwing** [comment]
fixed in ea12ff76c3
all of save, save As, save a Copy As work
