### ISSUE TITLE
Firebug in external window broken

### ISSUE THREAD

**Issue by johnwells** [MikeRatcliffe/Acebug#28]
Acebug doesn't work when using Firebug's "Open Firebug in New Window" option. Syntax highlighting and theme are broken, it seems that Acebug is loaded as the save and load buttons do open save and load dialogs, but saving and loading don't work. Run and Dir print

```
in:0>>>
undefined
```

when trying to run anything.

**Comment by nightwing** [comment]
for which versions of firebug and acebug does this happen?

**Comment by johnwells** [comment]
Firebug 1.83 with Acebug commit 2dc1d66b2c86f31cc08ae5827dad9a33bccae022

**Comment by nightwing** [comment]
didn't notice this because i am using Firebug1.9
fixed in 4b3c36555a
thanks
