### ISSUE TITLE
Website http://www.msi-stuff.com/acebug/ has unrelated content

### ISSUE THREAD

**Issue by mrjcleaver** [MikeRatcliffe/Acebug#30]
Hi Mike,

Perhaps you can host it somewhere else?

Thanks, M.

**Comment by MikeRatcliffe** [comment]
Thanks for pointing this out ... fixed.

The new URL is:
http://www.flailingmonkey.com/acebug/

**Comment by mrjcleaver** [comment]
Great, thanks Mike.
