### ISSUE TITLE
Don't work "Edit" on HTML tab

### ISSUE THREAD

**Issue by collapsus** [MikeRatcliffe/Acebug#33]
when Acebug add-on active, in firebug 1.9.0b5, on HTML tab don't work "edit HTML" (when i turn off Acebug, "edit HTML" start working)

**Comment by nightwing** [comment]
unfortunately breaking change was introduced in last firebug beta
and amo is very slow with reviews :(

for 1.9.0b5+ you need to use acebug 1.9.0 from [here](https://addons.mozilla.org/en-US/firefox/addon/acebug/versions/)

thanks for reporting this,
i've added a note about this on amo too
