### ISSUE TITLE
Themes option not working.

### ISSUE THREAD

**Issue by edubkendo** [MikeRatcliffe/Acebug#35]
I'm using Acebug 1.9.1 with firebug 1.9.1 on Firefox 10.0.2 Mozilla Firefox for Ubuntu on Ubuntu 11.10 Unity, and everything else in the add-on works beautifully, but I am unable to select a theme. I use textmate themes and bundles in Sublime Text, so I'm familiar with installing those, but didn't see any instructions about doing so in order to use themes with this add-on. Do they need to be installed somewhere or are the themes included with the acebug add-on?

**Comment by MikeRatcliffe** [comment]
Themes are included by default and available under the Acebug options menu. It seems like there is some issue with selecting themes from there ... thanks for the bug report!
