### ISSUE TITLE
add 'coffeescript' tag on Mozilla Add-ons website

### ISSUE THREAD

**Issue by roryokane** [MikeRatcliffe/Acebug#37]
On [its Mozilla Add-ons page](https://addons.mozilla.org/en-US/firefox/addon/acebug/), Acebug does not have 'coffeescript' as a tag. I think it should.

When I heard of the release of [CoffeeConsole for Chrome](https://github.com/snookca/CoffeeConsole) a few days ago, I searched on Google for a similar extension for Firefox. I clicked a link to [a search page for the tag coffeescript](https://addons.mozilla.org/en-US/firefox/tag/coffeescript) on Mozilla Add-ons. That search brings up only the add-on [xqjs](https://addons.mozilla.org/en-US/firefox/addon/xqjs/?src=search), which made me think there was no Firebug-integrated CoffeeScript console currently existing. If Acebug had been tagged 'coffeescript', I would have found Acebug then. (I found Acebug now only because someone [replied](http://news.ycombinator.com/item?id=3811774) to a comment I wrote in which I wished for such an extension.)

**Comment by nightwing** [comment]
Thanks!
i completely forgot about the tags. added `coffee` and `coffeescript` now

i saw post about CoffeeConsole early when there were only a few comments, thought i'll look again later to see if someone mentions firefox or acebug, but forgot:)

if you have any suggestions on making acebug better or anything is unclear in documentation, feel free to create issues here
thank you very much
