### ISSUE TITLE
Broken right-click context menu in Net Panel

### ISSUE THREAD

**Issue by igrigorov** [MikeRatcliffe/Acebug#38]
Hi there,

I noticed the following issue: when I have Acebug enabled, the right-click menu on the Net panel does not show up. To be precise, it seems to try to show up, but it seems has no entries, just a tiny square appears instead of it.

Once I disable Acebug, the context menu is ok again.

Please note that the context menu on the Console panel for XMLHttpRequests are intact, no problem there.

**Comment by nightwing** [comment]
will be in next release, thanks for the report!
