### ISSUE TITLE
find a better way to add xpi

### ISSUE THREAD

**Issue by nightwing** [MikeRatcliffe/Acebug#4]
adding xpi to project makes repository unnecessarily large, and fetching slow 
we should find better place for putting it, and add link into readme

also while making xpi we should remove all .git folders to make xpi small
in foximirror i have script for that.

**Comment by MikeRatcliffe** [comment]
I will host the xpi ... that is no problem ... I am midway through putting a decent web page together at the moment.

Why is fetching slow for you ... where are you based?

I did not realize that there were git folders throughout the repository, of course they should be removed. I will put some scripts together ... depending on my mood I might use Windows, Linux or OSX.

**Comment by nightwing** [comment]
> where are you based?
> i am in Armenia with 512kb internet connection,
> and acebug's repository is ~36mb while ace is 3mb only
> seems like version control doesn't work well with archives

**Comment by MikeRatcliffe** [comment]
The web page won't be long but I need to make it look professional, add autoupdate etc.

Installing the xpi does not work properly from GitHub anyway because I have no control of GitHub's mime type configuration.

**Comment by nightwing** [comment]
thanks.
