### ISSUE TITLE
Coffeescript syntax highlighting doesn't work anymore in 1.9.4

### ISSUE THREAD

**Issue by Arkham** [MikeRatcliffe/Acebug#40]
When I enable coffescript from Acebug console, all syntax highlighting capabilities are lost:

![acebug 1.9.4](http://i.imgur.com/nxdZx.png)

While it used to work in 1.9.2:

![acebug 1.9.2](http://i.imgur.com/PR6yD.png)

**Comment by nightwing** [comment]
thanks! this is fixed in https://addons.mozilla.org/en-us/firefox/addon/acebug/versions/?page=1#version-1.10.0

**Comment by Arkham** [comment]
Thanks, it works great now :)
