### ISSUE TITLE
support for livescript

### ISSUE THREAD

**Issue by cocodrino** [MikeRatcliffe/Acebug#41]
first congratulation..this extension is awesome!..

secondly I wish know if would be possible port livescript to acebug, similar to coffescript...livescript is based in coffeescript and coco, similar syntax to coffeescript but much more functional...would be cool use it inside firbug...thanks man..and keep doing a good job...

**Comment by nightwing** [comment]
> this extension is awesome!..

thanks!

> port livescript to acebug

unfortunately ace doesn't support livescript atm
but for someone who knows livescript, it shouldn't be too hard to modify coffeescript mode to work with livescript
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/coffee_highlight_rules.js
with that in place, adding livescript to acebug would be trivial.

could you help?

**Comment by gkz** [comment]
https://github.com/gkz/LiveScript/blob/master/lib/mode-ls.js

needs updating though

**Comment by nightwing** [comment]
great!
could you open pull request to ace with that?
or should i just take and modify it?

**Comment by gkz** [comment]
well I would wait until 1.0 is out, which should be soon hopefully

**Comment by gjtorikian** [comment]
I see LiveScript is at 1.0.1, can it be pulled into Ace now ?

**Comment by gkz** [comment]
yes

**Comment by nightwing** [comment]
added this in the latest version
