### ISSUE TITLE
Firebug’s “Edit HTML” is broken with Acebug in Firefox 14

### ISSUE THREAD

**Issue by roryokane** [MikeRatcliffe/Acebug#42]
Since upgrading to Firefox 14 (from 13), I can’t edit the HTML of a node from the HTML tab. When I select a node, such as `▶ <div class="form-actions">`, and then click Edit in the top-left of the Firebug panel, nothing happens. It’s the same when I right-click a node and choose “Edit HTML…” from its context menu – nothing happens. Except, only two times out of many tries, clicking “Edit” has deleted the selected node instead of doing nothing.

I have tried disabling all of my Firebug add-ons except Acebug, and HTML editing still didn’t work. Then, when I disabled Acebug, it worked. When I re-enabled Acebug, it stopped working again. Acebug seems to be the cause.

**Comment by nightwing** [comment]
thanks for reporting!
this should be fixed in https://addons.mozilla.org/en-US/firefox/addon/acebug/versions/?page=1#version-1.10.0, please test.
see https://groups.google.com/forum/?hl=en&fromgroups#!topic/firebug/dimNgHoMhO0 for related discussion

**Comment by roryokane** [comment]
Thanks for the help. After installing and enabling [Version 1.10.0](https://addons.mozilla.org/en-US/firefox/addon/acebug/versions/#version-1.10.0), I have no more problems. Editing the HTML works again, and the editor is powered-up by Acebug.
