### ISSUE TITLE
Firebug 1.11.1 html tab ->edit is broken

### ISSUE THREAD

**Issue by tylik1** [MikeRatcliffe/Acebug#44]
Recently I've updated a new firebug version 1.11.1 on Firefox 17.0.1 and I can't use html live edit no more. It doesn't save the edited result. When I turn off Acebug addon, it works fine. On the previous versions of firebug everything worked fine also. 
Actions to reproduce the problem:
1. Press HTML tab
2. Press Edit in the panel below.
3. Edit some html or simply delete.
4. Unpress Edit button.
Any help appreciated.

**Comment by nightwing** [comment]
Yes, noticed it today. Should be fixed with https://github.com/MikeRatcliffe/Acebug/commit/e4423342fa5930c80788bb3dfa81b313aee7f71c

But i am not sure if i want to upload it to amo, they have very long reviews:(
Would it be ok if i only add it in github downloads?

**Comment by tylik1** [comment]
Yes sure! Thanks for the quick response :)

**Comment by nightwing** [comment]
hmm github have removed downloads,
you can use this https://docs.google.com/open?id=0B_seCdCeqTcIbEtoa01WM1ZTOVU for now

**Comment by tylik1** [comment]
Thanks, now it works!
