### ISSUE TITLE
Outdated URLs

### ISSUE THREAD

**Issue by sujeet** [MikeRatcliffe/Acebug#47]
Found a couple of outdated URLs. Initially, it gave a feeling that Acebug development has been stopped :(
- Firefox addon page (https://addons.mozilla.org/en-us/firefox/addon/acebug/) links to non-existent github repo.
- Readme links to http://www.flailingmonkey.com/acebug/ which gives a 404.

**Comment by MikeRatcliffe** [comment]
Thanks for the feedback, these issues are now fixed.

If you find any other issues then please let us know.
