### ISSUE TITLE
Graphical glitches

### ISSUE THREAD

**Issue by OctoD** [MikeRatcliffe/Acebug#51]
![image](https://f.cloud.github.com/assets/2328211/1097343/bd32bc16-170f-11e3-858e-ca74b00a347c.png)

![image](https://f.cloud.github.com/assets/2328211/1097356/f2167940-170f-11e3-9b4b-0c6dea981678.png)

I've noticed some ui glitches with the last firebug/firefox update (1.12.1 / 23.0.1 ).

In console panel some icons are missing.
When i switch from an active firebug instance to one not active, the whole ui breaks.

**Comment by nightwing** [comment]
please try https://github.com/MikeRatcliffe/Acebug/releases/download/v1.12-pre/Acebug.xpi

**Comment by OctoD** [comment]
Fixed! Thanks a lot :+1:
