### ISSUE TITLE
Show large command line with acebug, then switching panel breaks firebug in Minefield

### ISSUE THREAD

**Issue by sroussey** [MikeRatcliffe/Acebug#6]
Show large command line with acebug, then switching panel breaks firebug in Minefield. The other panels are not selectable.

**Comment by MikeRatcliffe** [comment]
Seems like some issue with initialization ... I will take a look.

**Comment by MikeRatcliffe** [comment]
Seems like onDomLoad never gets fired in the Minefield version ... it works fine without the listener anyway.

Fixed.
