### ISSUE TITLE
Need to create a fake setAttribute method

### ISSUE THREAD

**Issue by MikeRatcliffe** [MikeRatcliffe/Acebug#9]
We need to create a fake largeCommandLine.getAttribute method to prevent an error onload.

**Comment by nightwing** [comment]
maybe it's better to use
.__noSuchMethod__ = function(){}

**Comment by MikeRatcliffe** [comment]
I'm not sure what you mean ... I was going to use:
    getAttribute :function(){}

**Comment by MikeRatcliffe** [comment]
aha ... I see, it makes sense now.

**Comment by MikeRatcliffe** [comment]
Fixed in devel branch
